doc-warnings: yes
test-warnings: no
strictness: veryhigh
autodetect: yes
requirements:
    - requirements.txt
ignore-paths:
    - docs
ignore-patterns:
    - (^|/)docs(/|$)
    - setup\.py
python-targets:
    - 2
pyflakes:
  disable:
    - F401
pylint:
  disable:
    - too-few-public-methods
    - too-many-instance-attributes
